action: save
split: train
modality: ["RGB"]
name: D1_train_RGB_10_dense
total_batch: 128
batch_size: 32
resume_from: ./saved_models/I3D_SourceOnlyD1

save:
  num_clips: 5
  dense_sampling:
    RGB: True
  num_frames_per_clip:
    RGB: 10

train:
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 10

test:
  num_clips: 5
  dense_sampling:
    RGB: True
  num_frames_per_clip:
    RGB: 10

dataset:
  annotations_path: train_val
  shift: D1-D1
  workers: 4
  stride: 2
  resolution: 224
  RGB:
    data_path: ek_data/frames
    tmpl: "img_{:010d}.jpg"
  Event:
    rgb4e: 6

models:
  RGB:
    model: I3D
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
    weight_i3d_rgb: './pretrained_i3d/rgb_imagenet.pt'

